package ss.hotel.password;

/**
 * Representation of a password with flexible validation rules.
 * Uses a Checker to determine password acceptability.
 */
public class Password {

    /**
     * The checker used to validate passwords.
     */
    private final Checker checker;
    
    /**
     * The initial password that can be shared with clients.
     */
    private final String initPass;
    
    /**
     * The current password.
     */
    private String password;

    /**
     * Constructs a Password with the given Checker.
     * The initial password is generated by the checker.
     *
     * @param checker the Checker to use for password validation
     */
    public Password(Checker checker) {
        this.checker = checker;
        this.initPass = checker.generatePassword();
        this.password = initPass;
    }

    /**
     * Constructs a Password with a default BasicChecker.
     */
    public Password() {
        this(new BasicChecker());
    }

    /**
     * Returns the Checker used by this Password.
     *
     * @return the Checker instance
     */
    public Checker getChecker() {
        return checker;
    }

    /**
     * Returns the initial password.
     *
     * @return the initial password string
     */
    public String getInitPass() {
        return initPass;
    }

    /**
     * Test if a given string is an acceptable password
     * according to this Password's Checker.
     *
     * @param suggestion Word that should be tested
     * @return true if suggestion is acceptable
     */
    public boolean acceptable(String suggestion) {
        return checker.acceptable(suggestion);
    }

    /**
     * Tests if a given word is equal to the current password.
     *
     * @param test Word that should be tested
     * @return true if test is equal to the current password
     */
    public boolean testWord(String test) {
        return password.equals(test);
    }

    /**
     * Changes this password.
     *
     * @param oldpass The current password
     * @param newpass The new password
     * @return true if oldPass is equal to the current password
     *         and newpass is an acceptable password
     */
    public boolean setWord(String oldpass, String newpass) {
        if (testWord(oldpass) && acceptable(newpass)) {
            this.password = newpass;
            return true;
        }
        return false;
    }
}